# This is a basic workflow to help you get started with Actions

name:
  Hit Render APIs

  # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: '*/14 * * * *' # Runs every 14 minutes
  push:
    branches:
      - main

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Run JavaScript file
        run: node index.js
